import Link from 'next/link'
import './globals.css'
import ThemeProvider from '@/components/theme-provider'
import Analytics from '@/components/analytics'
import ModeToggle from '@/components/mode-toggle'
import GoTop from '@/components/go-top'

export const metadata = {
  title: "Eric's Blog",
  description: 'Generated by create next app'
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang='en'>
      <body
        className={`antialiased min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-slate-50`}
      >
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <div className='max-w-4xl mx-auto py-4'>
            <header className='px-4 py-6 sticky top-0 z-10 backdrop-blur-sm bg-white/80 dark:bg-slate-950/80'>
              <div className='flex items-center justify-between'>
                <ModeToggle />
                <nav className='ml-auto text-sm font-medium space-x-6'>
                  <Link href='/'>首頁</Link>
                  <Link href='/about'>關於</Link>
                </nav>
              </div>
            </header>
            <h1 className='p-4 font-bold text-center text-4xl text-green'>
              Eric&apos;s Blog
            </h1>
            <main className='px-4 mt-6 z-10'>{children}</main>
            <GoTop />
          </div>
          <Analytics />
        </ThemeProvider>
      </body>
    </html>
  )
}
